twl_weekday_morning_peak_hour = [["tsw, twh, 2.0, 0"],
                                 ["twh, kwh, 2.0, 0"],
                                 ["kwh, kwf, 2.0, 0"],
                                 ["kwf, lak, 2.0, 0"],
                                 ["lak, mef, 2.0, 0"],
                                 ["mef, lck, 2.0, 0"],
                                 ["lck, csw, 2.0, 0"],
                                 ["csw, ssp, 2.0, 0"],
                                 ["ssp, pre, 2.0, 0"],
                                 ["pre, mok, 2.0, 0"],
                                 ["mok, ymt, 2.0, 0"],
                                 ["ymt, jor, 2.0, 0"],
                                 ["jor, tst, 2.0, 0"],
                                 ["tst, adm, 2.0, 0"],
                                 ["adm, cen, 2.0, 0"]]

twl_weekday_evening_peak_hour = [["tsw, twh, 2.0, 0"],
                                 ["twh, kwh, 2.0, 0"],
                                 ["kwh, kwf, 2.0, 0"],
                                 ["kwf, lak, 2.0, 0"],
                                 ["lak, mef, 2.0, 0"],
                                 ["mef, lck, 2.0, 0"],
                                 ["lck, csw, 2.0, 0"],
                                 ["csw, ssp, 2.0, 0"],
                                 ["ssp, pre, 2.0, 0"],
                                 ["pre, mok, 2.0, 0"],
                                 ["mok, ymt, 2.0, 0"],
                                 ["ymt, jor, 2.0, 0"],
                                 ["jor, tst, 2.0, 0"],
                                 ["tst, adm, 2.0, 0"],
                                 ["adm, cen, 2.0, 0"]]

ktl_weekday_morning_peak_hour = [["wha, hom, 2.0, 0"],
                                 ["hom, ymt, 2.0, 0"],
                                 ["ymt, mok, 2.0, 0"],
                                 ["mok, pre, 2.0, 0"],
                                 ["pre, skm, 2.0, 0"],
                                 ["skm, kot, 2.0, 0"],
                                 ["kot, lof, 2.0, 0"],
                                 ["lof, wts, 2.0, 0"],
                                 ["wts, dih, 2.0, 0"],
                                 ["dih, chh, 2.0, 0"],
                                 ["chh, kob, 2.0, 0"],
                                 ["ntk, kwt, 2.0, 0"],
                                 ["kwt, lat, 2.0, 0"],
                                 ["lat, yat, 2.0, 0"],
                                 ["yat, tik, 2.0, 0"]]

ktl_weekday_evening_peak_hour = [["wha, hom, 2.0, 0"],
                                 ["hom, ymt, 2.0, 0"],
                                 ["ymt, mok, 2.0, 0"],
                                 ["mok, pre, 2.0, 0"],
                                 ["pre, skm, 2.0, 0"],
                                 ["skm, kot, 2.0, 0"],
                                 ["kot, lof, 2.0, 0"],
                                 ["lof, wts, 2.0, 0"],
                                 ["wts, dih, 2.0, 0"],
                                 ["dih, chh, 2.0, 0"],
                                 ["chh, kob, 2.0, 0"],
                                 ["ntk, kwt, 2.0, 0"],
                                 ["kwt, lat, 2.0, 0"],
                                 ["lat, yat, 2.0, 0"],
                                 ["yat, tik, 2.0, 0"]]

tcl_weekday_morning_peak_hour = [["hok, kow, 3.3, 0"],
                                 ["kow, lak, 3.3, 0"],
                                 ["lak, nac, 3.3, 0"],
                                 ["nac, oly, 3.3, 0"],
                                 ["oly, sun, 3.3, 0"],
                                 ["sun, tsy, 3.3, 0"],
                                 ["tsy, tuc, 3.3, 0"]]

tcl_weekday_evening_peak_hour = [["hok, kow, 3.3, 0"],
                                 ["kow, lak, 3.3, 0"],
                                 ["lak, nac, 3.3, 0"],
                                 ["nac, oly, 3.3, 0"],
                                 ["oly, sun, 3.3, 0"],
                                 ["sun, tsy, 3.3, 0"],
                                 ["tsy, tuc, 3.3, 0"]]
